name: rimae
channels:
  - pytorch
  - nvidia
  - pytorch3d
  - bottler
  - iopath
  - fvcore
  - conda-forge
  - defaults
dependencies:
  # Python & core
  - python=3.10
  - pip=23.3
  # PyTorch 2.1 + CUDA 12.1
  - pytorch=2.1.1
  - torchvision=0.16.1
  - pytorch-cuda=12.1  # meta‑pkg from nvidia channel
  # Core libs
  - pytorch3d  # CUDA 12 사전 빌드가 없을 경우 README 참고
  - nvidiacub
  - iopath
  - fvcore
  - pyyaml
  - scikit-learn
  - scipy
  - pandas
  - matplotlib
  - h5py
  - tqdm
  - einops
  - joblib
  - tensorboard
  - scikit-image
  - jupyterlab
  - black
  - flake8
  - pip:
    - pointnet2_ops_lib
    - timm
    - easydict
    - termcolor
    - open3d
    - usort
    - "git+https://github.com/LucasColas/Pointnet2_PyTorch.git#egg=pointnet2_ops&subdirectory=pointnet2_ops_lib"
    - "https://github.com/unlimblue/KNN_CUDA/releases/download/0.2/KNN_CUDA-0.2-py3-none-any.whl"
    - chamfer-distance
    - emd
    - imageio
    - plotly
    - opencv-python 